version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/React-FullStarter-Kit

    branches:
      only:
        - master

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build the image
          command: docker-compose up -d

      - run:
          name: Build the application
          command: docker-compose exec app yarn build:app

      - run:
          name: Test the application
          command: docker-compose exec app yarn test:app

      - run:
          name: Test coverage integration
          command: docker-compose exec app yarn codecov -- --token=${CODECOV_TOKEN}

      - deploy:
          name: Deploy to Firebase
          command: docker-compose exec app yarn deploy -- --token ${FIREBASE_TOKEN}

      - deploy:
          name: Deploy to Heroku
          command: |
            docker login -u="Shyam Chen" -p="${HEROKU_TOKEN}" registry.heroku.com
            docker build -f Dockerfile.prod -t registry.heroku.com/react-by-example/web .
            docker push registry.heroku.com/react-by-example/web
